variable "resource_group_name" {}
variable "resource_group_location" {}
variable "virtual_network_name" {}
variable "subnet_name" {}
variable "subnet_id" {}
variable "network_interface_name" {}
variable "network_interface_ids" {}
variable "ip_configuration_name" {}
variable "private_ip_address_allocation" {}
variable "address_space" {}
variable "address_prefixes" {}
variable "virtual_network_size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "os_disk_caching" {}
variable "storage_account_type" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "image_version" {}